# Format: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
name: FHIR IG Feedback Form
description: File feedback on the FHIR IG
body:
  - type: textarea
    id: element
    attributes:
      label: FHIR Element
      description: If this feedback is specific to a particular resource field please enter it here.
      placeholder: ResourceName.elementName
    validations:
      required: false
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: Please describe your comment, issue, or suggestion here.
      placeholder: e.g. I think we should use CarePlan instead of RequestGroup because...
    validations:
      required: true
